"""The paired-significance section, end to end -- 28 values the certifying tool never read.

The document cites `paired_significance.json` at four places and quotes its numbers at
three of them. Nothing in the checker reads any of them: `grep` finds zero occurrences of
`0.268187`, `McNemar`, `is_level_paired`, `0.0635`, `32 对 32`, `64 行`, `0.5403`, `0.5535`,
`0.0132`, `cross_algorithm_paired` or `paper_setting_paired` in the 850-line tool.

That includes the paragraph the document itself introduces as closing a hole -- "第 9 节新增的
`paper_setting_paired`" -- where the whole point is that the two runs' aggregate accuracies
are equal while their per-row predictions are not, so the paired test had to be *run* rather
than inferred. A paragraph arguing that a value must be computed rather than inferred, with
every value in it uncomputed by the tool that certifies the document.

The record is regenerated by the pipeline, so these are live numbers, not history. Read here
against the records:

  * `cross_algorithm_paired.lr5e-5`  -- its two members, and the -0.0278 quoted beside them
  * `paper_setting_paired`           -- the equal accuracies, the delta, both CI ends, p,
                                        the 252-row unit, the 64 differing rows, and 32/32
  * the macro-F1 pair                -- 0.0132 (0.5403 against 0.5535)
  * `is_level_paired`                -- the delta, both CI ends, p, and 16 against 24

Two of these deserve their own note.

**0.5535 is not the G=8 run.** The macro-F1 sentence sits two lines after the G=32 sentence
and quotes 0.5535 against G=32's 0.5403. The obvious reading -- the neighbouring run -- is
wrong: 0.5535 is GRPO(G=4) lr5e-5, the *other member of the same pair* the paragraph is
about, and GSPO(G=8) lr5e-5's macro-F1 is 0.5014. An item pins which run it is, because the
sentence does not name it and that is how a reader gets it wrong.

**The 252-row unit is checked against the benchmark, not the record.** Every delta and CI
endpoint in this file is an integer multiple of 1/252 (the benchmark's row count) -- that is
what pairing on 252 rows means. So the same item also verifies the record was computed over
the row set the document names: if the benchmark gains or loses a row and the record is not
regenerated, the endpoints stop lying on the grid and this fires. The record's prose says
"the same 252 rows" but prose is not a checkable source; the benchmark file is.

The mcnemar counts are compared group-wise, not as a sorted pair, wherever the document
distinguishes the two sides ("token 错而 sequence 对 16 行，反之 24 行") -- sorting would
accept the two directions swapped, which is the whole content of the claim.
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path("/root/autodl-fs/wafer-vlm")
CHECKER = ROOT / "tools/check_quantified_claims.py"
BAK = "/tmp/check_quantified_claims.py.bak-patch110"

ANCHOR = 'g = anchor("5.2.2: the Scratch per-class maximum", P_SCRATCH)\n'

BLOCK = r'''# ------------- the paired-significance section: what the document quotes from it
# Four sentences quote outputs/reports/paired_significance.json and section 9 calls it the
# instrument that answers what the marginal CI rule cannot. No item read any of the values.
# The record is regenerated by the pipeline, so every one of these is live.
PR = REP / "paired_significance.json"
_BENCH = ROOT / "benchmarks/wafer_bench_v1/classification.jsonl"
if not PR.is_file():
    cmp("the paired-significance record", "present", "absent",
        why="three sentences in this document quote values from it")
else:
    _pr = json.loads(PR.read_text(encoding="utf-8"))

    def _tag(lbl):
        """The record's tag for a run label: GSPO(G=8) lr5e-5 -> GSPO_G8_lr5e5."""
        _m = re.fullmatch(r"([A-Za-z]+)\(G=(\d+)\) (lr[\d.eE+-]+)", lbl)
        return (f"{_m.group(1)}_G{_m.group(2)}_{_m.group(3).replace('-', '')}"
                if _m else None)

    _T2L = {t: n for n in runs if (t := _tag(n))}
    _GRP = lambda lbl: f"{lbl.split('(')[0]}(G={lbl.split('G=')[1].split(')')[0]})"
    _nb = (sum(1 for _l in _BENCH.read_text(encoding="utf-8").split("\n") if _l.strip())
           if _BENCH.is_file() else None)
    NUMF = r"[−\-]?[\d.]+"

    def _f(s):
        return float(s.replace("−", "-"))

    def _dec(s):
        """The precision the document quotes a value at, so the comparison is made
        there. The record carries six decimals and the document four: comparing the
        record's -0.031746 against the quoted -0.0317 at record precision would report
        a stale sentence where the sentence is simply rounded."""
        return len(s.split(".")[1]) if "." in s else 0

    def _quoted(s, val):
        return _f(s) == round(val, _dec(s))

    def _on_grid(v, n):
        """Is v an integer multiple of 1/n, to the record's 6 decimals?"""
        return n is not None and abs(round(v * n) - v * n) <= 1e-3

    # ------------------------------------------- cross_algorithm_paired.lr5e-5
    _caps = _pr.get("cross_algorithm_paired", {}).get("lr5e-5")
    _gm = re.search(r"的两个成员是 \*\*([A-Za-z]+\(G=\d+\)) 与 ([A-Za-z]+\(G=\d+\))\*\*",
                    text)
    if _caps and _gm:
        cmp("5.2.2: the two members of cross_algorithm_paired.lr5e-5",
            sorted([_gm.group(1), _gm.group(2)]),
            sorted([_GRP(_T2L[_caps["grpo_token"]]), _GRP(_T2L[_caps["gspo_sequence"]])]),
            why="the record's two headings name the runs; the sentence's members must be "
                "the same two, or the -0.0278 quoted beside them is some other contrast")
        _gd = re.search(r"那个 ([−\-][\d.]+) 是「G=8 对 G=4」的准确率差", text)
        if _gd:
            cmp("5.2.2: the cross_algorithm_paired accuracy delta quoted",
                _f(_gd.group(1)),
                round(_caps["accuracy_delta_gspo_minus_grpo"], 4),
                kind="count", pattern=r"那个 ([−\-][\d.]+) 是「G=8 对 G=4」的准确率差",
                group=1)
        else:
            cmp("5.2.2: the cross_algorithm_paired delta", "the phrase", "absent",
                why="the sentence quotes it; if this phrase is gone nothing reads it")

    # ------------------------------------------------- paper_setting_paired
    _psp = _pr.get("paper_setting_paired")
    if _psp:
        _a32 = present[_T2L[_psp["to"]]]["accuracy"] if _T2L.get(_psp["to"]) else None
        _a04 = (present[_T2L[_psp["from"]]]["accuracy"]
                if _T2L.get(_psp["from"]) else None)
        cmp("5.2.2: the two runs' aggregate accuracies are actually equal",
            _a32 == _a04, True,
            why="the paragraph's entire argument is that equality of aggregates does not "
                "imply equality per row; if the aggregates are not equal the argument is "
                "about a different situation")
        _ge = re.search(r"完全相同，都是 ([\d.]+)（Δ = ([−\-]?[\d.]+)）", text)
        if _ge:
            cmp("5.2.2: the equal accuracy the paragraph quotes",
                _f(_ge.group(1)), round(_a32, _dec(_ge.group(1))), kind="count",
                pattern=r"完全相同，都是 ([\d.]+)（Δ = ([−\-]?[\d.]+)）", group=1)
            cmp("5.2.2: the delta it quotes beside them", _f(_ge.group(2)),
                round(_psp["accuracy_delta_g32_minus_grpo4"], _dec(_ge.group(2))),
                kind="count",
                pattern=r"完全相同，都是 ([\d.]+)（Δ = ([−\-]?[\d.]+)）", group=2)
        else:
            cmp("5.2.2: the equal accuracy", "the phrase", "absent",
                why="the sentence quotes an accuracy and a zero delta; both are unread if "
                    "this phrase is rewritten")
        # The delta, both CI ends and p, from the sentence that introduces section 9's
        # instrument.
        P_PSP = (r"`paper_setting_paired`：Δ = (" + NUMF + r")、95% CI \[(" + NUMF +
                 r"), \+([\d.]+)\]\s*、?\s*`p` = ([\d.]+)")
        _gp = re.search(P_PSP, text)
        if _gp:
            _ci = _psp["delta_ci95_rows"]
            for _i, (_lab, _val) in enumerate((
                    ("the accuracy delta", _psp["accuracy_delta_g32_minus_grpo4"]),
                    ("the lower CI end", _ci[0]),
                    ("the upper CI end", _ci[1]),
                    ("p", _psp["mcnemar"]["p_exact_two_sided"])), start=1):
                cmp(f"5.2.2: paper_setting_paired {_lab}", _f(_gp.group(_i)),
                    round(_val, _dec(_gp.group(_i))),
                    kind="count", pattern=P_PSP, group=_i)
        else:
            cmp("5.2.2: paper_setting_paired's delta, CI and p", "the phrase", "absent",
                why="this is the sentence that introduces the paired instrument; if it "
                    "cannot be found, three of its numbers are read by nothing")
        # The population, the differing rows, and the complementarity.
        P_PSP_ROWS = (r"但两者在 (" + NUM + r") 行里有 (" + NUM + r") 行判断不同，恰好 (" +
                      NUM + r") 对 (" + NUM + r") 互补")
        _gr = re.search(P_PSP_ROWS, text)
        _mc = _psp["mcnemar"]
        _two = [_mc["grpo_wrong_gspo_right"], _mc["grpo_right_gspo_wrong"]]
        if _gr:
            cmp("5.2.2: the row count the paired test is over", cn2int(_gr.group(1)), _nb,
                kind="count", pattern=P_PSP_ROWS, group=1)
            cmp("5.2.2: the rows the two runs classify differently", cn2int(_gr.group(2)),
                sum(_two), kind="count", pattern=P_PSP_ROWS, group=2)
            cmp("5.2.2: the complementarity of those rows (the pair, in order)",
                [cn2int(_gr.group(3)), cn2int(_gr.group(4))], _two,
                why="the sentence's point is that the differing rows are exactly "
                    "complementary; swapping the two directions keeps the sum and loses "
                    "the claim")
        else:
            cmp("5.2.2: the paired row count and its split", "the phrase", "absent",
                why="the 252-row unit and the 64-row split are unread without it")
        _g64 = re.search(r"会漏掉这 (" + NUM + r") 行的互换", text)
        if _g64:
            cmp("5.2.2: the same 64 rows, the third time the sentence states them",
                cn2int(_g64.group(1)), sum(_two), kind="count",
                pattern=r"会漏掉这 (" + NUM + r") 行的互换", group=1)
        else:
            cmp("5.2.2: the differing-row count repeated after the em dash", "the phrase",
                "absent",
                why="the sentence states the count three times; the three must agree")
        # The macro-F1 pair, and which run the second value belongs to.
        _g32, _oto = _T2L.get(_psp["to"]), _T2L.get(_psp["from"])
        # The numeral is on the next line: the sentence breaks after 低. A pattern with a
        # literal space there matches nothing, and -- with no absent-branch -- would have
        # read zero of these four numbers while reporting green.
        P_MF1 = r"macro-F1 上 G=32 低\s*([\d.]+)（([\d.]+) 对 ([\d.]+)）"
        _gmf = re.search(P_MF1, text)
        if _gmf and _g32 and _oto:
            _mf = {_n: present[_n]["macro_f1"] for _n in (_g32, _oto)}
            # The sentence names the second run's value but not the run. Mapped back
            # through every report: it must be the pair's other member. Two lines above
            # stands the G=8 run, whose macro-F1 is 0.5014, and reading the sentence as
            # "the neighbouring run" is the natural mistake.
            _mapped = [n for n in runs
                       if round(present[n]["macro_f1"], 4)
                       == round(float(_gmf.group(3)), 4)]
            cmp("5.2.2: the run the second macro-F1 in that pair belongs to", _mapped,
                [_oto],
                why="the sentence does not name it; it has to be the other member of the "
                    "same pair, not the G=8 run quoted two lines above")
            cmp("5.2.2: G=32's macro-F1 in that pair", float(_gmf.group(2)),
                round(_mf[_g32], 4), kind="count",
                pattern=P_MF1, group=2)
            cmp("5.2.2: the macro-F1 quoted against it", float(_gmf.group(3)),
                round(_mf[_oto], 4), kind="count",
                pattern=P_MF1, group=3)
            cmp("5.2.2: how much lower G=32's macro-F1 is", float(_gmf.group(1)),
                round(abs(_mf[_g32] - _mf[_oto]), 4), kind="count",
                pattern=P_MF1, group=1)
        else:
            cmp("5.2.2: the macro-F1 pair", "the phrase", "absent",
                why="three numbers and an unnamed subject; all four are unread without it")

    # ------------------------------------------------------ is_level_paired
    _isl = _pr.get("is_level_paired")
    P_ISL = (r"准确率差（sequence − token）= \*\*(" + NUMF + r")\*\*，95% 置信区间 \*\*\[(" +
             NUMF + r"), \+([\d.]+)\]\*\*（包含 0），\s*McNemar 精确检验 `p = ([\d.]+)`（token "
             r"错而 sequence 对 (" + NUM + r") 行，反之 (" + NUM + r") 行）")
    _gi = re.search(P_ISL, text)
    if _isl and _gi:
        _ci = _isl["delta_ci95_rows"]
        _mc = _isl["mcnemar"]
        for _i, (_lab, _val) in enumerate((
                ("the accuracy delta", _isl["accuracy_delta_sequence_minus_token"]),
                ("the lower CI end", _ci[0]),
                ("the upper CI end", _ci[1]),
                ("p", _mc["p_exact_two_sided"]),
                ("the rows token got wrong and sequence right",
                 _mc["token_wrong_sequence_right"]),
                ("the rows token got right and sequence wrong",
                 _mc["token_right_sequence_wrong"])), start=1):
            _v = cn2int(_gi.group(_i)) if _i >= 5 else round(_f(_gi.group(_i)), 6)
            _want = _val if _i >= 5 else round(_val, _dec(_gi.group(_i)))
            cmp(f"5.2.2: is_level_paired {_lab}", _v, _want,
                kind="count", pattern=P_ISL, group=_i)
        cmp("5.2.2: p is quoted to six decimals but the split is not sorted",
            _f(_gi.group(4)) == round(_mc["p_exact_two_sided"], 6), True,
            why="the two directions are named separately, so sorting them would accept "
                "the claim with its sides swapped")
    else:
        cmp("5.2.2: the is_level_paired sentence", "the phrase", "absent",
            why="the only single-variable IS-level contrast in the document; its six "
                "numbers are read by nothing without it")

    # The row grid: every delta and CI end in this record is k/252 for the benchmark's
    # 252 rows. Checked here rather than trusted, because the record is regenerated by
    # the pipeline and the benchmark is still draft_pending_human_review: if it gains a
    # row and the record is not recomputed, these stop being multiples of 1/n.
    _off = []
    for _name, _blk in (("cross_algorithm_paired.lr5e-5",
                         _pr.get("cross_algorithm_paired", {}).get("lr5e-5")),
                        ("paper_setting_paired", _pr.get("paper_setting_paired")),
                        ("is_level_paired", _pr.get("is_level_paired"))):
        if not _blk:
            continue
        _vals = [v for k, v in _blk.items() if "delta" in k and isinstance(v, float)]
        _vals += [v for k, v in _blk.items() if k == "delta_ci95_rows" for v in v]
        for _v in _vals:
            if not _on_grid(_v, _nb):
                _off.append((_name, _v))
    cmp(f"the paired record's values lie on the 1/{_nb} row grid of the benchmark",
        [], _off,
        why="accuracies paired over the benchmark's rows move in steps of 1/n; a value "
            "off the grid means the record was computed over a different row set than "
            "the sentence names")
    for _name in ("cross_algorithm_paired.lr5e-5", "paper_setting_paired",
                  "is_level_paired"):
        _blk = (_pr.get("cross_algorithm_paired", {}).get("lr5e-5")
                if _name.startswith("cross") else _pr.get(_name))
        if _blk:
            print(f"         {_name}: delta={_blk.get('accuracy_delta_gspo_minus_grpo', _blk.get('accuracy_delta_g32_minus_grpo4', _blk.get('accuracy_delta_sequence_minus_token')))} "
                  f"ci={_blk['delta_ci95_rows']} p={_blk['mcnemar']['p_exact_two_sided']}")

'''

c = CHECKER.read_text(encoding="utf-8")
shutil.copy2(CHECKER, BAK)

for what, cond in (("the insertion point", c.count(ANCHOR) == 1),
                   ("the paired items", "P_PSP" not in c and "is_level_paired" not in c)):
    if not cond:
        sys.exit(f"{what} is not as expected; nothing written")

c = c.replace(ANCHOR, BLOCK + ANCHOR, 1)
CHECKER.write_text(c, encoding="utf-8")

r = subprocess.run([sys.executable, "-m", "py_compile", str(CHECKER)],
                   capture_output=True, text=True)
if r.returncode != 0:
    shutil.copy2(BAK, CHECKER)
    sys.exit(f"the patched checker does not compile, restored:\n{r.stderr}")

print("the paired-significance section is now read: 4 sentences, their deltas, CIs, p "
      "values, row counts, splits and members.")
print("\n--- re-running the checker ---")
r = subprocess.run([sys.executable, str(CHECKER)], capture_output=True, text=True,
                   cwd=str(ROOT))
out = r.stdout.strip().splitlines()
for ln in out:
    s_ = ln.strip()
    if ("paired" in s_ or "McNemar" in s_ or "macro-F1" in s_ or "grid" in s_
            or "cross_algorithm" in s_ or "row count" in s_ or "differing" in s_
            or "complementarity" in s_ or "aggregate" in s_ or "delta" in s_
            or "CI end" in s_ or "p" == s_[:1] and "p [" in s_):
        print("  " + s_)
if r.stderr.strip():
    print("--- stderr ---")
    for ln in r.stderr.strip().splitlines()[-12:]:
        print("  " + ln)
print("  ...")
for ln in out[-5:]:
    print("  " + ln.strip())
if r.returncode != 0:
    shutil.copy2(BAK, CHECKER)
    sys.exit(f"\nthe checker is not green (exit {r.returncode}); RESTORED -- a quoted "
             f"paired value and its record disagree, and that is the finding")
print("\nchecker green: every value the document quotes from the paired record is read "
      "against it, and the record's row grid against the benchmark")
